Issue 10: Import Job for Opportunity Data from beta.sam
recro/medulla pull request #19
Opened 2021-09-29 14:09 UTC by sushilkumarss-sdn

- [x] You've included unit or integration tests for your change, where applicable.
- [x] You've included inline docs for your change, where applicable.
- [x] There's an open issue for your PR that you are making. Please open an issue to discuss changes or new features.

**PR Title**
Summary of the changes.

**PR Description**
Detail 1
Detail 2

Fixes #10

2021-09-29 16:16 UTC, AndrewBabbitt97 commented on src/Medulla.Frontend/Client/Medulla.Frontend.Client.csproj
> +﻿  <Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">
There should be no modifications to this project for this PR

2021-09-29 16:36 UTC, AndrewBabbitt97 commented
@sushilkumarss-sdn Please go over comments and rework into a background service. This and the contacts service are all supposed to be .NET background workers, not WebAPIs.

The project name you can use for the worker project is Medulla.Actions.SamGov and the tests in Medulla.Actions.SamGov.Tests.

There should be no modifications to the existing projects in this PR at all.

2021-10-01 10:40 UTC, sushilkumarss-sdn commented
> @sushilkumarss-sdn Please go over comments and rework into a background service. This and the contacts service are all supposed to be .NET background workers, not WebAPIs.
> 
> The project name you can use for the worker project is Medulla.Actions.SamGov and the tests in Medulla.Actions.SamGov.Tests.
> 
> There should be no modifications to the existing projects in this PR at all.

@AndrewBabbitt97, I have pushed the latest changes as per your comment, I reverted the changes from Medula.Frontend.Server and created 2 different projects i.e Medulla.Actions.SamGov and the tests in Medulla.Actions.SamGov.Tests.

2021-10-01 12:00 UTC, AndrewBabbitt97 commented
@sushilkumarss-sdn this still isn't a .NET background worker.

This should not be a WebAPI project. Use the .NET background worker template.

2021-10-04 09:09 UTC, AndrewBabbitt97 requested changes
Other notes:

- Start checking the messages section in the Visual Studio error list, it tells you of styling rules you are missing. We will eventually be enforcing this through checks on pull requests.
- Start using XMLDoc on all methods, properties, classes, etc. Will allow us to generate full documentation for Medulla down the line.

That's mostly it. Should be good to merge after you resolve the issues.

2021-10-04 09:09 UTC, AndrewBabbitt97 commented on src/Medulla.Actions.SamGov/Services/OpportunityServices.cs
> +            bool isSucess = false;
use var instead of bool

2021-10-04 09:09 UTC, AndrewBabbitt97 commented on src/Medulla.Actions.SamGov/Services/OpportunityServices.cs
> +                HttpResponseMessage Res = await client.GetAsync(url);
method variables should always start with a lowercase letter

2021-10-04 09:09 UTC, AndrewBabbitt97 commented on src/Medulla.Actions.SamGov/Services/OpportunityServices.cs
> +                await System.IO.File.WriteAllTextAsync($"opportunity_{DateTime.Now.ToString("MMddyyyyss")}.json", response);
Can be simplified to `await File.WriteAllTextAsync($"opportunity_{DateTime.Now:MMddyyyyss}.json", response);`

2021-10-04 09:09 UTC, AndrewBabbitt97 commented on src/Medulla.Actions.SamGov/Services/OpportunityServices.cs
> +            using (var client = new HttpClient())
Can be simplified to `using var client = new HttpClient();`

2022-01-30 07:31 UTC, closed without merging